/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ShutDownLinux */

#ifndef _Included_ShutDownLinux
#define _Included_ShutDownLinux
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ShutDownLinux
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ShutDownLinux_shutdown (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
