/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ShutDownWindows */

#ifndef _Included_ShutDownWindows
#define _Included_ShutDownWindows
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ShutDownWindows
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ShutDownWindows_shutdown (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
